# Generated by Django 4.2.4 on 2023-09-08 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date_question_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 15, 46, 12, 666897, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
