# Generated by Django 4.2.4 on 2023-09-10 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 13, 23, 59, 913141, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
